repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_checkov
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_validate
      - id: terrascan
        args:
          - --args=--non-recursive
      - id: tfupdate
